### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by vultix** [shlomiassaf/ng-cli-packagr-tasks#5]
I love and use this plugin for my libraries, and need to update to Angular 8.  Shouldn't be a lot of work to update.

**Comment by shlomiassaf** [comment]
Angular 8 comes with new CLI features, one of it is the new Builders API.

I don't know if it's backward compatible, I assume its not.

So there is some work for me here:

- Learn the new API
- Adjust and refactor to fit it.

It also means the next version will not work with angular < 8

I'll have to work on this cause i'm using this package myself :)

**Comment by shlomiassaf** [comment]
OK, 

I have something that might be ready in [this branch](https://github.com/shlomiassaf/ng-cli-packagr-tasks/tree/angular-v8)

I can't publish it because I did not test it at all, so if you want to help and tell me if it work, I'll appreciate it!

Thanks.

**Comment by shlomiassaf** [comment]
OK, version 4.0.0 is published, supports angular v8
